# This rule is essential for your React single-page application (SPA).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# These headers enhance your site's security.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # This Content-Security-Policy (CSP) is configured to allow Firebase services to run securely.
    Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://apis.google.com https://www.gstatic.com;
    connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://www.googleapis.com;
    frame-src 'self' https://accounts.google.com;
    img-src 'self' data: https:;
    style-src 'self' 'unsafe-inline';
    object-src 'none';
    base-uri 'self';
    """
