# from repo root
git rm --cached netlify.toml 2>/dev/null || true
rm -f netlify.toml

cat > netlify.toml <<'TOML'
[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build:noop"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  timeout = 25

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
TOML

git add netlify.toml
git commit -m "Fix: replace netlify.toml with minimal valid config"
git push
