[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# -------- SPA routing (only the app) --------
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# (Optional) If you want the ROOT to be a SPA too, uncomment:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# IMPORTANT: Do NOT add a catch-all 200 redirect that includes "/.netlify/*"
# Netlify automatically serves functions under /.netlify/functions/*

# -------- Global security headers --------
[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options        = "DENY"
  Referrer-Policy        = "strict-origin-when-cross-origin"
  Permissions-Policy     = "geolocation=(), microphone=(), camera=()"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# -------- CSP for the app (no invalid sources; no unsafe-eval) --------
[[headers]]
  for = "/app/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://www.gstatic.com https://www.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://apis.google.com;
    connect-src 'self' https://firestore.googleapis.com https://*.googleapis.com https://*.firebaseio.com https://www.googleapis.com https://www.gstatic.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: https://lh3.googleusercontent.com;
    font-src 'self' https://fonts.gstatic.com data:;
    frame-src https://accounts.google.com;
    base-uri 'self';
    form-action 'self';
  """

# -------- Cache standards JSON for speed --------
[[headers]]
  for = "/standards/*"
  [headers.values]
  Cache-Control = "public, max-age=86400, immutable"
