# /netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    base-uri 'self';
    object-src 'none';
    img-src 'self' data: blob:;
    font-src 'self' data:;
    style-src 'self' 'unsafe-inline';
    script-src 'self';
    connect-src 'self'
      https://identitytoolkit.googleapis.com
      https://securetoken.googleapis.com
      https://firestore.googleapis.com
      https://www.googleapis.com
      https://oauth2.googleapis.com
      https://firebaseinstallations.googleapis.com
      https://firebasestorage.googleapis.com
      https://firebaseremoteconfig.googleapis.com;
    frame-src 'self' https://accounts.google.com https://*.firebaseapp.com;
    child-src 'self' https://accounts.google.com https://*.firebaseapp.com;
    frame-ancestors 'self';
    upgrade-insecure-requests;
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "0"
