# Netlify configuration for Synapse
[build]
command = "npm run build:noop"
publish = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# SPA routing for the app at /app/
[[redirects]]
from = "/app/*"
to = "/app/index.html"
status = 200

# Convenience redirect for /app (no trailing slash)
[[redirects]]
from = "/app"
to = "/app/index.html"
status = 200

# Security headers for the app
[[headers]]
for = "/app/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com;
    connect-src 'self' https://firestore.googleapis.com https://*.googleapis.com https://*.firebaseio.com https://www.googleapis.com https://www.gstatic.com /.netlify/functions;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: https://lh3.googleusercontent.com;
    font-src 'self' data: https://fonts.gstatic.com;
    frame-src https://accounts.google.com;
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "0"
```eof

### Key Rules in This Final Version

This configuration solves the errors by including:

* **`'unsafe-eval'`** in the `script-src` directive, which is required by the Firebase Authentication SDK.
* **`https://fonts.googleapis.com`** in the `style-src` directive, which allows the Google Fonts stylesheet to load.
* **`https://fonts.gstatic.com`** in the `font-src` directive, which allows the actual font files to be downloaded.

Replace the content of your `netlify.toml` file with this code, commit, and deploy. This will resolve the security policy issues.
