[build]
publish = "."
functions = "netlify/functions"
command = "npm run build:noop"

[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
timeout = 25

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
