[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build:noop"

# 👇 Pin Node for Netlify build & Functions
[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin", "@google/generative-ai", "node-fetch"]
  included_files = []
  timeout = 25

# Keep CSP permissive enough for in-browser Babel (unsafe-eval). If you remove Babel later, drop 'unsafe-eval'.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: data: blob:; connect-src 'self' https: data: blob:; script-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; style-src 'self' https: 'unsafe-inline'; worker-src 'self' blob:"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
