[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
  default-src 'self';
  script-src 'self' https://apis.google.com https://www.gstatic.com https://accounts.google.com;
  connect-src 'self' https://firestore.googleapis.com https://www.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com https://accounts.google.com https://firebasestorage.googleapis.com;
  img-src 'self' data: https:;
  style-src 'self' 'unsafe-inline';
  frame-src https://accounts.google.com https://apis.google.com;
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
