# Netlify configuration for Synapse (Headers are now managed in the UI)
[build]
  command = "npm run build:noop"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA routing for the app at /app/
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# Convenience redirect for /app (no trailing slash)
[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
