[build]
command = "npm run build:noop"
publish = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# App lives at /app/ (single-page app style)
[[redirects]]
from = "/app/*"
to = "/app/index.html"
status = 200
