# Netlify configuration for Synapse
[build]
command = "npm run build:noop"
publish = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# SPA routing for the app at /app/
[[redirects]]
from = "/app/*"
to = "/app/index.html"
status = 200

# Convenience redirect for /app (no trailing slash)
[[redirects]]
from = "/app"
to = "/app/index.html"
status = 200

# Security headers for the app
[[headers]]
for = "/app/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://www.gstatic.com https://www.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com;
    connect-src 'self' https://firestore.googleapis.com https://*.googleapis.com https://*.firebaseio.com https://www.googleapis.com https://www.gstatic.com /.netlify/functions;
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https://lh3.googleusercontent.com;
    font-src 'self' data:;
    frame-src https://accounts.google.com;
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "0"
