# Netlify configuration for Synapse (Headers are now in the _headers file)

[build]
  base    = "."
  command = "npm run build:noop"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA routing for the app
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
